
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: farmtrace
      POSTGRES_USER: farmtrace
      POSTGRES_PASSWORD: farmtrace123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farmtrace"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # FastAPI Application (uncomment when ready to run with Docker)
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql://farmtrace:farmtrace123@db:5432/farmtrace
  #     REDIS_URL: redis://redis:6379/0
  #     MINIO_ENDPOINT: minio:9000
  #   depends_on:
  #     - db
  #     - redis
  #     - minio
  #   volumes:
  #     - .:/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
  minio_data:
