// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdignsuttjamgbysydjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kaWduc3V0dGphbWdieXN5ZGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTA0OTQsImV4cCI6MjA2ODE4NjQ5NH0.sVnXBeDuMBFZR4CMWgtYT77-1q9YBUd34Qvl7KqFqDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});